### ISSUE TITLE
PrefMon doesn't seem to know how to handle extensions with unusual names

### ISSUE THREAD

**Issue by rmenessec** [diegocr/PrefMon#1]
Disconnect Search ( https://disconnect.me/search ), which is logged to the console by PrefMon simply as "Disconnect Search", doesn't seem to be possible to whitelist at present. It's changing proxy and search engine preferences. I've tried whitelisting via 'Disconnect Search:.*', which doesn't work. I'm not sure if I need an extension GUID here, or one of those very odd JetPack ("SDK") identifiers.

If I do need an extension GUID, it sure would be nice if PrefMon could find it on its own, or help me find it.

**Comment by diegocr** [comment]
Add `;Disconnect Search:network\.` to the end of the `Ignore By Add-On` option.

(I've tested that by installing the extension, so it must work)
